# Generated by Django 4.0.2 on 2022-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=224, null=True)),
                ('last_name', models.CharField(blank=True, max_length=224, null=True)),
                ('company_name', models.CharField(blank=True, max_length=224, null=True)),
                ('city', models.CharField(blank=True, max_length=224, null=True)),
                ('State', models.CharField(blank=True, max_length=224, null=True)),
                ('zip', models.IntegerField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=224, null=True)),
                ('web', models.CharField(blank=True, max_length=224, null=True)),
                ('age', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
